import { Check, ExternalLink, RefreshCw, Trash2, Undo2 } from "lucide-react";
import { useRef, useState } from "react";
import type { Action, Conversation, Feed, Snapshot } from "../shared/schema";
import { Dialog } from "./Dialog";
import { RunStatus } from "./AiPanel";
import { agentName } from "./format";

type Props = { removedFeeds: Feed[]; snapshot: Snapshot; folderId: string | null; act: (action: Action) => Promise<void>; perform: (action: Action) => void; openConversation: (conversation: Conversation) => void };

export function LibraryDialogs({ removedFeeds, snapshot, folderId, act, perform, openConversation }: Props) {
  const feedDialog = useRef<HTMLDialogElement>(null);
  const folderDialog = useRef<HTMLDialogElement>(null);
  const activityDialog = useRef<HTMLDialogElement>(null);
  const [feedError, setFeedError] = useState<string | null>(null);
  const [folderError, setFolderError] = useState<string | null>(null);
  const [adding, setAdding] = useState(false);
  const [saving, setSaving] = useState(false);
  const { state, connections } = snapshot;
  return <>
    <Dialog id="feed-dialog" title="フィードを追加" dialogRef={feedDialog} onClose={() => setFeedError(null)}><p className="dialog-description">読みたいサイトのRSS / Atom URLを登録します。</p><form onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setAdding(true); setFeedError(null); void act({ type: "feed.add", url: String(data.get("url") ?? ""), folderId: String(data.get("folder") ?? "") || null }).then(() => { form.reset(); feedDialog.current?.close(); }).catch((error: unknown) => setFeedError(error instanceof Error ? error.message : "追加できませんでした。")).finally(() => setAdding(false)); }}><label htmlFor="feed-url">フィードURL</label><input id="feed-url" name="url" type="url" placeholder="https://example.com/feed.xml" required autoComplete="off" aria-invalid={!!feedError} aria-describedby={feedError ? "feed-error" : undefined} /><label htmlFor="feed-folder">フォルダ</label><select id="feed-folder" name="folder"><option value="">フォルダなし</option>{state.folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select>{feedError ? <p className="form-error" id="feed-error" role="alert">{feedError}</p> : null}<div className="dialog-actions"><button className="secondary-button" type="button" commandfor="feed-dialog" command="close">キャンセル</button><button type="submit" className="primary-button" disabled={adding}>{adding ? "取得しています…" : "フィードを追加"}</button></div></form></Dialog>
    <Dialog id="folder-dialog" title={folderId ? "フォルダ名を変更" : "フォルダを作成"} dialogRef={folderDialog} onClose={() => setFolderError(null)}><form key={folderId ?? "new"} onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setSaving(true); setFolderError(null); void act({ type: "folder.save", id: folderId, name: String(data.get("name") ?? "") }).then(() => { form.reset(); folderDialog.current?.close(); }).catch((error: unknown) => setFolderError(error instanceof Error ? error.message : "保存できませんでした。")).finally(() => setSaving(false)); }}><label htmlFor="folder-name">フォルダ名</label><input id="folder-name" name="name" defaultValue={state.folders.find((folder) => folder.id === folderId)?.name ?? ""} placeholder="テクノロジー、デザイン…" required maxLength={60} aria-invalid={!!folderError} />{folderError ? <p className="form-error" role="alert">{folderError}</p> : null}<div className="dialog-actions"><button className="secondary-button" type="button" commandfor="folder-dialog" command="close">キャンセル</button><button type="submit" className="primary-button" disabled={saving}>{saving ? "保存中…" : "保存"}</button></div></form></Dialog>
    <Dialog id="connections-dialog" title="エージェント接続"><p className="dialog-description">MacにあるCLIのログインを使います。<br />Reedar専用のAPIキーは必要ありません。</p><div className="connections">{connections.map((connection) => <div key={connection.agent} className="connection-item"><div className="connection-title"><strong>{agentName[connection.agent]}</strong><span className={`connection-state connection-${connection.status}`}>{connection.status === "ready" ? <><Check size={12} />接続済み</> : connection.status === "checking" ? "確認中" : connection.status === "authentication" ? "ログインが必要" : connection.status === "unavailable" ? "未インストール" : connection.status === "unsupported" ? "連携準備中" : "接続エラー"}</span></div><p>{connection.detail}</p>{connection.status === "authentication" ? <div className="login-command">ターミナルで <code>{connection.agent === "claude" ? "claude auth login" : "codex login"}</code></div> : null}</div>)}</div><p className="dialog-footnote">記事の閲覧と会話に限定して接続します。ファイル操作、外部ツール、追加の権限要求は許可しません。</p><div className="dialog-actions"><button className="secondary-button" onClick={() => perform({ type: "connections.refresh" })}><RefreshCw size={13} />接続を再確認</button></div></Dialog>
    <Dialog id="activity-dialog" title="AIの会話" dialogRef={activityDialog}><div className="activity-list">{[...state.conversations].reverse().map((conversation) => { const last = conversation.messages.at(-1); return <button key={conversation.id} className="activity-row" onClick={() => { openConversation(conversation); activityDialog.current?.close(); }}><div><span>{agentName[conversation.agent]}</span>{last?.role === "assistant" ? <RunStatus state={last.state} /> : null}</div><strong>{conversation.source.title}</strong><p>{last?.text.slice(0, 120) || (last?.role === "assistant" ? last.state.status === "failed" ? last.state.error : last.state.status === "waiting" ? last.state.reason : last.state.status === "cancelled" ? "回答を中止しました" : last.state.status === "completed" ? "完了しました" : "回答を待っています" : "会話を開始できます")}</p><ExternalLink size={13} /></button>; })}{!state.conversations.length ? <p className="dialog-description">記事を開いて「AIと読む」を選ぶと、ここに会話が残ります。</p> : null}</div></Dialog>
    <Dialog id="organize-dialog" title="フィードの整理"><p className="dialog-description">フォルダの移動やフィードの削除ができます。削除したフィードは更新されなくなり、一覧から非表示になります。記事・スター・会話は保持され、ここから復元できます。進行中のAI回答は停止します。</p><div className="organize-list">{state.feeds.map((feed) => <div className="organize-row" key={feed.id}><label><span>{feed.title}</span><select aria-label={`${feed.title}のフォルダ`} value={feed.folderId ?? ""} onChange={(event) => perform({ type: "feed.move", id: feed.id, folderId: event.target.value || null })}><option value="">フォルダなし</option>{state.folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label><button className="icon-button remove-feed" aria-label={`${feed.title}を削除`} title="フィードを削除" onClick={() => perform({ type: "feed.remove", id: feed.id })}><Trash2 size={15} /></button></div>)}</div>{!state.feeds.length ? <p className="dialog-description">登録中のフィードはありません。</p> : null}{removedFeeds.length ? <details className="removed-feeds"><summary>削除済みのフィード（{removedFeeds.length}）</summary><div className="organize-list">{removedFeeds.map((feed) => <div key={feed.id} className="restore-row"><span>{feed.title}</span><button className="text-button" aria-label={`${feed.title}を復元`} onClick={() => perform({ type: "feed.restore", id: feed.id })}><Undo2 size={13} />復元</button></div>)}</div></details> : null}</Dialog>
  </>;
}
