import { ArrowDown, ArrowUp, Bot, Circle, ExternalLink, Star, X } from "lucide-react";
import type { Action, Article, Feed } from "../shared/schema";
import { domain, fullDate, readingMinutes } from "./format";

type Props = { article: Article | undefined; feed: Feed | undefined; aiOpen: boolean; toggleAi: () => void; perform: (action: Action) => void; previous: () => void; next: () => void; hasPrevious: boolean; hasNext: boolean };

export function Reader({ article, feed, aiOpen, toggleAi, perform, previous, next, hasPrevious, hasNext }: Props) {
  return <section className={`reader ${aiOpen ? "with-ai" : ""}`} aria-label="記事本文">
    <header className="reader-toolbar"><div className="toolbar-group"><button className="icon-button" aria-label="前の記事" onClick={previous} disabled={!hasPrevious}><ArrowUp size={17} /></button><button className="icon-button" aria-label="次の記事" onClick={next} disabled={!hasNext}><ArrowDown size={17} /></button></div>
      {article ? <div className="toolbar-group"><button className="icon-button" aria-label={article.read ? "未読に戻す" : "既読にする"} title={article.read ? "未読に戻す (M)" : "既読にする (M)"} onClick={() => perform({ type: "article.read", id: article.id, read: !article.read })}><Circle size={16} className={!article.read ? "unread-icon" : ""} /></button><button className={`icon-button ${article.starred ? "star-filled" : ""}`} aria-label={article.starred ? "スターを外す" : "スターを付ける"} aria-pressed={article.starred} title="スター (S)" onClick={() => perform({ type: "article.star", id: article.id, starred: !article.starred })}><Star size={17} /></button><a className="icon-button" href={article.url} target="_blank" rel="noopener noreferrer" aria-label="原文をブラウザで開く" title="原文を開く"><ExternalLink size={16} /></a><span className="toolbar-divider" /><button className={`ai-toggle ${aiOpen ? "active" : ""}`} onClick={toggleAi} aria-pressed={aiOpen}><Bot size={17} /><span>AIと読む</span>{aiOpen ? <X size={13} /> : null}</button></div> : null}
    </header>
    {article ? <div className="reader-scroll" key={article.id}><article className="article-body"><div className="article-source"><span>{feed?.title ?? domain(article.url)}</span><span>·</span><time dateTime={article.publishedAt}>{fullDate.format(new Date(article.publishedAt))}</time></div><h1>{article.title}</h1><div className="article-byline">{article.author ? <span>{article.author}</span> : null}<span>約{readingMinutes(article)}分で読めます</span></div><div className="article-html" dangerouslySetInnerHTML={{ __html: article.html }} />{!article.text ? <p className="muted">このフィードには本文が含まれていません。</p> : null}<a className="original-link" href={article.url} target="_blank" rel="noopener noreferrer">{domain(article.url)}で原文を読む<ExternalLink size={13} /></a></article></div> : <div className="reader-empty"><div className="empty-mark"><Bot size={32} strokeWidth={1.3} /></div><h2>読む。気になる。その先へ。</h2><p>左の記事を選んで読みはじめましょう。<br />気になることは、いつものAIと一緒に。</p><button className="text-button" commandfor="feed-dialog" command="show-modal">フィードを追加する</button></div>}
  </section>;
}
